const openBtn=document.getElementById('openBtn'), invitation=document.getElementById('invitation'), audio=document.getElementById('audio'), musicBtn=document.getElementById('musicBtn'), wave=document.getElementById('wave'), toast=document.getElementById('toast');
let petalsStarted=false;
function showToast(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}
function setPlaying(on){musicBtn.textContent=on?'❚❚':'▶';wave.classList.toggle('playing',on);}
async function playMusic(){try{await audio.play();setPlaying(true)}catch(e){setPlaying(false);showToast('Tap the ▶ button to start the music');}}
openBtn.addEventListener('click',()=>{invitation.classList.remove('hidden');document.body.style.overflowX='hidden';playMusic();setTimeout(()=>document.getElementById('invitation').scrollIntoView({behavior:'smooth',block:'start'}),180);if(!petalsStarted){petalsStarted=true;startPetals();}});
musicBtn.addEventListener('click',async()=>{if(audio.paused) await playMusic(); else {audio.pause();setPlaying(false)}});
audio.addEventListener('ended',()=>setPlaying(false));
audio.addEventListener('error',()=>showToast('Music file could not be loaded. Check assets/vaaroon-forever.mp3'));
const reveal=document.getElementById('revealDate'), date=document.getElementById('date');reveal.addEventListener('click',()=>{date.classList.add('revealed');reveal.disabled=true;reveal.querySelector('span').textContent='Revealed';});
document.querySelectorAll('[data-rsvp]').forEach(btn=>btn.addEventListener('click',()=>{const msg=encodeURIComponent(`Naveen & Tripti's Engagement Invitation 💛\n11 November 2026\nRama Babu Ka Bagicha, Hanuman Mandir, Deoria\n\n${btn.dataset.rsvp}`);window.open(`https://wa.me/?text=${msg}`,'_blank');}));
document.getElementById('calendarBtn').addEventListener('click',()=>{const start='20261111T120000',end='20261111T160000';const ics=['BEGIN:VCALENDAR','VERSION:2.0','BEGIN:VEVENT','SUMMARY:Naveen & Tripti — Engagement Ceremony','DTSTART:'+start,'DTEND:'+end,'LOCATION:Rama Babu Ka Bagicha, Hanuman Mandir, Deoria, U.P.','DESCRIPTION:Engagement ceremony of Naveen & Tripti.','END:VEVENT','END:VCALENDAR'].join('\r\n');const blob=new Blob([ics],{type:'text/calendar'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Naveen-Tripti-Engagement.ics';a.click();URL.revokeObjectURL(a.href);});
function startPetals(){for(let i=0;i<24;i++){setTimeout(()=>{const p=document.createElement('span');p.className='petal';p.style.left=Math.random()*100+'%';p.style.setProperty('--drift',(Math.random()*160-80)+'px');p.style.animationDuration=(6+Math.random()*7)+'s';p.style.animationDelay=(Math.random()*2)+'s';document.querySelector('.petals').appendChild(p);setTimeout(()=>p.remove(),15000)},i*280)}}
